In [73]:
import numpy as np
import pandas as pd
import pickle
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [2]:
datapath = "../Data/"
houses = pd.read_csv(datapath+"houses.csv")
houses_preprocessed = pd.read_csv(datapath+"houses-preprocessed.csv", encoding='ISO-8859-1')
houses_preprocessed_buurten = pd.read_csv(datapath+"houses-preprocessed-buurten.csv", encoding='ISO-8859-1')

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (7,11,22,24,25,30,33,40,50,67,73) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
houses.to_pickle("../Data/houses.pickle")
houses_preprocessed.to_pickle("../Data/houses_preprocessed.pickle")
houses_preprocessed_buurten.to_pickle("../Data/houses_preprocessed_buurten.pickle")

In [4]:
df = pd.read_pickle("../Data/houses_preprocessed_buurten.pickle")

In [5]:
for col in df.columns:
    print(col)

Unnamed: 0
buurt_code
V1.x
startprice
endprice
url
realtor
buurt_naam
wijk_code
bathroom.ligbad
bathroom.douche
bathroom.toilet
bathroom.jacuzzi
bathroom.sauna
bathroom.zitbad
bathroom.stoomcabine
feature.mechanischeventilatie
feature.tvkabel
feature.rookkanaal
feature.lift
feature.dakraam
feature.elektra
feature.vliering
feature.zonnecollectoren
feature.elektrischedeur
feature.buitenzonwering
feature.schuifpui
feature.stromendwater
feature.airconditioning
feature.verwarming
feature.alarminstallatie
feature.zwembad
feature.sauna
feature.glasvezelkabel
feature.stoomcabine
feature.rolluiken
feature.jacuzzi
feature.satellietschotel
feature.windmolen
housetype
housesubtype
housesubsubtype
tuinoppervlakte
tuindiepte
tuinbreedte
voortuinoppervlakte
voortuindiepte
voortuinbreedte
voorlopigenergielabel
energielabel
orientation.aanvaarwater
orientation.aanwater
orientation.incentrum
orientation.vrijuitzicht
orientation.inwoonwijk
orientation.beschutteligging
orientation.aanrustigeweg
orientatio

In [6]:
len(df.columns)

212

In [7]:
a = [col for col in df.columns if 'jaar:aantal' in col]
a

['0 tot 15 jaar:aantal',
 '15 tot 25 jaar:aantal',
 '25 tot 45 jaar:aantal',
 '45 tot 65 jaar:aantal']

In [8]:
len(df)

78807

In [9]:
df['bathroom.ligbad'].value_counts()

0    51899
1    26858
2       50
Name: bathroom.ligbad, dtype: int64

In [10]:
droppable = ['Unnamed: 0', 'V1.x', 'V1.y', 'url', 'realtor', 'buurt_naam', 'feature.tvkabel', 'feature.rookkanaal',
             'feature.elektra', 'feature.elektrischedeur', 'feature.buitenzonwering', 'feature.stromendwater',
             'feature.verwarming', 'feature.windmolen', 'certificate.', 'housenumber', 'postcodenummerdeel', 'address', 
             'startdate', 'enddate', 'duration', 'Onderwerpen:Wijken en buurten', 'Meest voorkomende postcode:code', 
             'Soort regio:omschrijving', 'Woningvoorraad:aantal', 'Indelingswijziging wijken en buurten:code', 
             'Oppervlakte totaal:ha', 'Oppervlakte land:ha', 'Oppervlakte water:ha']

droppable_lookat = ['startprice', 'wijk_code', 'municipality', 'postcode', 'latitude', 'longitude', 'Gemeentenaam:naam', 
                    'Percentage bewoond:%']

addable =['feature.mechanischeventilatie', 'feature.dakraam', 'feature.rolluiken', 'insulation.vollediggesoleerd', 
          'insulation.dakisolatie', 'insulation.muurisolatie', 'insulation.vloerisolatie', 'insulation.dubbelglas', 
          'insulation.gedeeltelijkdubbelglas']

addable_lookat = ['bathroom.ligbad', 'bathroom.douche', 'bathroom.toilet', 'bathroom.jacuzzi', 'bathroom.sauna',
                  'bathroom.zitbad', 'bathroom.stoomcabine', 'feature.zonnecollectoren', 'feature.schuifpui',
                  'feature.airconditioning', 'feature.alarminstallatie', 'feature.satellietschotel', 'insulation.voorzetramen', 
                  'insulation.geenspouw', 'insulation.ecobouw', 'insulation.geenisolatie', 'certificate.kiwaveiligwonenkeurmerk', 
                  'certificate.energieprestatieadvies', 'certificate.politiekeurmerk', 'certificate.giwwaarborgcertificaat', 
                  'certificate.woningborggarantiecertificaat', 'certificate.swkgarantiecertificaat', 
                  'certificate.algemenewoningkeur', 'certificate.brandveiligheid', 'certificate.ergieprestatieadvies', 
                  'certificate.bouwkundigekeuring', 'certificate.huisgarantie']

comparing = ['feature.vliering', 'housetype', 'voorlopigenergielabel', 'orientation.aanvaarwater', 'incentrum', 'vrijuitzicht',
             'inwoonwijk', 'orientation.vrijuitzicht', 'orientation.inwoonwijk', 'orientation.beschutteligging',
             'orientation.aanrustigeweg', 'gardenorientation', 'gardenaccessiblefromtherear', 'details.gestoffeerd', 
             'garage.parkeerplaats', 'garage.inpandig', 'garage.aangebouwdestenengarage', 'garage.vrijstaandestenengarage', 
             'balcony.balkon', 'Mate van stedelijkheid:code', 'Aantal inkomensontvangers\xa0\xa0:aantal', 'yearofconstruction']

comparing_lookat = ['feature.zwembad', 'feature.sauna', 'feature.glasvezelkabel', 'feature.stoomcabine', 'feature.stoomcabine',
                    'feature.jacuzzi', 'housesubtype', 'housesubsubtype', 'tuinoppervlakte', 'tuindiepte', 'tuinbreedte', 
                    'voortuinoppervlakte', 'voortuindiepte', 'voortuinbreedte', 'energielabel',  'orientation.openligging',
                    'orientation.aandrukkeweg', 'orientation.aanpark', 'orientation.aanbosrand', 
                    'orientation.inbosrijkeomgeving', 'orientation.buitenbebouwdekom', 'orientation.landelijkgelegen', 
                    'details.monument', 'details.gedeeltelijkgestoffeerd', 'details.gemeubileerd', 
                    'details.dubbelebewoningmogelijk', 'details.beschermdstadsofdorpsgezicht', 'details.monumentaalpand', 
                    'details.kluswoning', 'details.dubbelebewoningaanwezig', 'details.gedeeltelijkverhuurd', 
                    'garage.parkeerkelder', 'garage.garagemogelijk', 'garage.garagebox', 'garage.nietaanwezig', 
                    'garage.welmogelijk', 'garage.carport', 'garage.souterrain', 'rooftype', 'roofmaterial', 'soortbouw', 
                    'storage', 'autoplekken', 'balcony.fransbalkon', 'balcony.dakterras', 'rooms', 'bedrooms', 'livingspace', 
                    'lotsurface', 'province', 'volume', 'constructionperiod', 'Afstand tot huisartsenpraktijk:km', 
                    'Afstand tot grote supermarkt:km', 'Afstand tot grote supermarkt:km', 'Afstand tot kinderdagverblijf:km', 
                    'Afstand tot school:km', 'Scholen binnen 3 km:aantal', 'Personen per soort uitkering; Bijstand:aantal', 
                    'Personen per soort uitkering; AO:aantal', 'Personen per soort uitkering; WW:aantal', 
                    'Personen per soort uitkering; AOW:aantal', 'Gemiddeld inkomen per inkomensontvanger\xa0:x 1 000 euro', 
                    'Gemiddeld inkomen per inwoner\xa0:x 1 000 euro', '40% personen met laagste inkomen:%', 
                    '20% personen met hoogste inkomen:%', 'Huishoudens met een laag inkomen:%', 
                    'Huish. onder of rond sociaal minimum:%', 'Woningvoorraad:aantal', 'Gemiddelde woningwaarde:x 1 000 euro', 
                    'Percentage eengezinswoning:%', 'Koopwoningen:%', 'In bezit woningcorporatie:%', 
                    'In bezit overige verhuurders:%', 'Bouwjaar vanaf 2000:%', 'Westers totaal:aantal', 
                    'Niet-westers totaal:aantal', 'Geboorte totaal:aantal', 'Eenpersoonshuishoudens:aantal', 
                    'Huishoudens zonder kinderen:aantal', 'Huishoudens met kinderen:aantal', 
                    'Gemiddelde huishoudensgrootte:aantal', 'Bevolkingsdichtheid:aantal inwoners per km²', 
                    'Aantal inwoners:aantal', 'Mannen:aantal', '0 tot 15 jaar:aantal', '15 tot 25 jaar:aantal', 
                    '25 tot 45 jaar:aantal', '45 tot 65 jaar:aantal', 'Ongehuwd:aantal', 'Gehuwd:aantal', 'Gescheiden:aantal', 
                    'A Landbouw, bosbouw en visserij:aantal', 'B-F Nijverheid en energie:aantal', 
                    'G+I Handel en horeca:aantal', 'H+J Vervoer, informatie en communicatie:aantal', 
                    'K-L Financiële diensten, onroerend goed:aantal', 'M-N Zakelijke dienstverlening:aantal', 
                    'R-U Cultuur, recreatie, overige diensten:aantal', 'Afstand tot oprit hoofdverkeersweg:km', 
                    'Afstand tot treinstations totaal:km', 'Afstand tot belangrijk overstapstation:km']

# 1st Step : Clustering different houses
The underlying assumption for clustering is that different housing clusters behave differently in terms of price. E.g. the presence of a garden is not expected to be important for a 50 m2 house while it is expected to be important for a 200m2 one. We start by performing PCA on the features which are not string type

In [62]:
# get columns with types which are suitable for pca aka non string columns
list_pca = df[comparing_lookat].dtypes[df[comparing_lookat].dtypes!=object].index
list_pca

Index(['feature.zwembad', 'feature.sauna', 'feature.glasvezelkabel',
       'feature.stoomcabine', 'feature.stoomcabine', 'feature.jacuzzi',
       'tuinoppervlakte', 'tuindiepte', 'tuinbreedte', 'voortuinoppervlakte',
       'voortuindiepte', 'voortuinbreedte', 'orientation.openligging',
       'orientation.aandrukkeweg', 'orientation.aanpark',
       'orientation.aanbosrand', 'orientation.inbosrijkeomgeving',
       'orientation.buitenbebouwdekom', 'orientation.landelijkgelegen',
       'details.monument', 'details.gedeeltelijkgestoffeerd',
       'details.gemeubileerd', 'details.dubbelebewoningmogelijk',
       'details.beschermdstadsofdorpsgezicht', 'details.monumentaalpand',
       'details.kluswoning', 'details.dubbelebewoningaanwezig',
       'details.gedeeltelijkverhuurd', 'garage.parkeerkelder',
       'garage.garagemogelijk', 'garage.garagebox', 'garage.nietaanwezig',
       'garage.welmogelijk', 'garage.carport', 'garage.souterrain',
       'autoplekken', 'balcony.fransbalko

PCA does not work with NaN values. For this reason we separate columns wich contain NaN values from those which do not.

In [64]:
list_not_null_pca = list_pca[~df[list_pca].isnull().any()]
list_not_null_pca

Index(['feature.zwembad', 'feature.sauna', 'feature.glasvezelkabel',
       'feature.stoomcabine', 'feature.stoomcabine', 'feature.jacuzzi',
       'orientation.openligging', 'orientation.aandrukkeweg',
       'orientation.aanpark', 'orientation.aanbosrand',
       'orientation.inbosrijkeomgeving', 'orientation.buitenbebouwdekom',
       'orientation.landelijkgelegen', 'details.monument',
       'details.gedeeltelijkgestoffeerd', 'details.gemeubileerd',
       'details.dubbelebewoningmogelijk',
       'details.beschermdstadsofdorpsgezicht', 'details.monumentaalpand',
       'details.kluswoning', 'details.dubbelebewoningaanwezig',
       'details.gedeeltelijkverhuurd', 'garage.parkeerkelder',
       'garage.garagemogelijk', 'garage.garagebox', 'garage.nietaanwezig',
       'garage.welmogelijk', 'garage.carport', 'garage.souterrain',
       'balcony.fransbalkon', 'balcony.dakterras', 'Woningvoorraad:aantal',
       'Westers totaal:aantal', 'Niet-westers totaal:aantal',
       'Geboorte t

In [66]:
#Performing Pca on the features which do not contain Nan values
#In PCA feature scaling is also important * Here we do not perform feature scaling 

pca = PCA(n_components=3)
pca.fit(df[list_not_null_pca])
PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

print(pca.explained_variance_ratio_)  
print(pca.singular_values_) 

[0.94397279 0.03185481 0.01275712]
[1368475.66650136  251388.17787014  159086.59617291]


In [65]:
list_null_pca = list_pca[df[list_pca].isnull().any()]
list_null_pca

Index(['tuinoppervlakte', 'tuindiepte', 'tuinbreedte', 'voortuinoppervlakte',
       'voortuindiepte', 'voortuinbreedte', 'autoplekken', 'rooms', 'bedrooms',
       'livingspace', 'lotsurface', 'volume',
       'Afstand tot huisartsenpraktijk:km', 'Afstand tot grote supermarkt:km',
       'Afstand tot grote supermarkt:km', 'Afstand tot kinderdagverblijf:km',
       'Afstand tot school:km', 'Scholen binnen 3 km:aantal',
       'Personen per soort uitkering; Bijstand:aantal',
       'Personen per soort uitkering; AO:aantal',
       'Personen per soort uitkering; WW:aantal',
       'Personen per soort uitkering; AOW:aantal',
       'Gemiddeld inkomen per inkomensontvanger :x 1 000 euro',
       'Gemiddeld inkomen per inwoner :x 1 000 euro',
       '40% personen met laagste inkomen:%',
       '20% personen met hoogste inkomen:%',
       'Huishoudens met een laag inkomen:%',
       'Huish. onder of rond sociaal minimum:%',
       'Gemiddelde woningwaarde:x 1 000 euro', 'Percentage eengezins

In this step, since pca does not work with Nan Values we want to add a value in each column which symbolizes Nan. This value is selected based on variable type - whether the column is int float or binary - and what the column represents. Here we find only float columns contain NaN values. As a first approach we are going to map the values -1 to all NaN values.

In [67]:
df[list_null_pca].dtypes

tuinoppervlakte                                          float64
tuindiepte                                               float64
tuinbreedte                                              float64
voortuinoppervlakte                                      float64
voortuindiepte                                           float64
voortuinbreedte                                          float64
autoplekken                                              float64
rooms                                                    float64
bedrooms                                                 float64
livingspace                                              float64
lotsurface                                               float64
volume                                                   float64
Afstand tot huisartsenpraktijk:km                        float64
Afstand tot grote supermarkt:km                          float64
Afstand tot grote supermarkt:km                          float64
Afstand tot kinderdagverb

In [72]:
df_pca = df[list_pca].copy()
df_pca.fillna(-1,inplace=True)
df_pca.isnull().any().any()

False

## Perform feature preprocessing and PCA

In [75]:
#using standard scaler on the data 
scaler = StandardScaler()
scaler.fit(df_pca)
df_scaled = scaler.transform(df_pca)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:617: DataConversionWarning: Data with input dtype bool, int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:3: DataConversionWarning: Data with input dtype bool, int64, float64 were all converted to float64 by StandardScaler.
  app.launch_new_instance()


In [99]:
#Performing pca on the scaled data 
pca = PCA(n_components=5)
pca.fit(df_scaled)
PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

print(pca.explained_variance_ratio_)  
#print(pca.singular_values_) 

[0.23756436 0.07583336 0.04865652 0.03428816 0.03097758]


In [100]:
pca.explained_variance_ratio_.sum()

0.4273199700609366

In [101]:
#Performing Pca on the unscaled data 
pca = PCA(n_components=5)
pca.fit(df_pca)
PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

print(pca.explained_variance_ratio_)  
#print(pca.singular_values_) 

[0.47783548 0.3163971  0.18062552 0.01112315 0.00594465]


In [102]:
pca.explained_variance_ratio_.sum()

0.9919259011152686

We observe that performing pca on the unscaled data yields much better results than performing pca on the scaled ones. This may be because of the scaler we used, or because we transformed different data types.

# To - DO
Clustering 